### PR TITLE
2025.05.13 component preset cleanups

### PR DESCRIPTION
**Pull request by dbarry9**
## Pull Request Description
Various cleanups to address warnings introduced in PR #284.

These changes have been tested on systems containing the NVIDIA Hopper and Blackwell architectures.

## Author Checklist
- [ ] **Description**
_Why_ this PR exists. Reference all relevant information, including _background_, _issues_, _test failures_, etc
- [ ] **Commits**
_Commits_ are self contained and only do one thing
_Commits_ have a header of the form: `module: short description`
_Commits_ have a body (whenever relevant) containing a detailed description of the addressed problem and its solution
- [ ] **Tests**
The PR needs to pass all the tests

### CODE REVIEW

**Comment by Treece-Burgess** [comment]
I am reviewing this PR.

**Comment by Treece-Burgess** [comment]
Tested on Heimdall at Oregon (1 * RTX 5080) with Cuda Toolkit 12.8.

The compile time warning:
```
papi_avail.c:573:17: warning: too many arguments for format [-Wformat-extra-args]
  573 |         printf( "%-*s%-11s%-8s%-16s\n |Long Description|\n", maxSymLen,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
papi_avail.c:687:21: warning: too many arguments for format [-Wformat-extra-args]
  687 |             printf( "%-*s%-11s%-8s%-16s\n |Long Description|\n", maxCompSymLen,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Does not occur any more with these changes. The PAPI build was successful and the utilities function properly.

Spacing looks good too.

**Review by Treece-Burgess — APPROVED** [review]

**Comment by tokey-tahmid** [comment]
Tested the latest changes on H100 and RTX5080 with cuda/12.8.0, everything looks good.
